import { ROUTES as FALLBACK_ROUTES } from './routes.js'; import { getRoute,getSchedule,mapUrl } from './schedule.js';
const API_URL='https://script.google.com/macros/s/AKfycbzdG_ARbbPgMdlPteqFLakZHR5EEkT4Lb3YFDbXW_I_OyrDKo8l0_KrQLjnncxj_M9q/exec',DATA_KEY='trasy2.routes',SYNC_KEY='trasy2.lastSuccessfulSync',FAIL_KEY='trasy2.firstFailedSync',THREE_DAYS=259200000;
const $=s=>document.querySelector(s),routeSelect=$('#routeSelect'),timeSelect=$('#timeSelect'),message=$('#formMessage'),connectionStatus=$('#connectionStatus'),staleWarning=$('#staleWarning'); let routes=loadCached()??FALLBACK_ROUTES,syncing=false,offline=true,wakeLock=null,wakeWanted=false,currentAdminRoute=null;
const views=['#selectionView','#scheduleView','#adminLoginView','#adminResetView','#adminView','#adminChangePasswordView','#adminEditView']; function showView(id){views.forEach(v=>$(v).hidden=v!==id);scrollTo(0,0)}
renderRoutes();syncRoutes();setInterval(updateStatus,60000);window.addEventListener('online',syncRoutes);window.addEventListener('focus',syncRoutes);
routeSelect.onchange=()=>{const r=getRoute(routes,routeSelect.value);timeSelect.replaceChildren(new Option(r?'Wybierz godzinę':'Najpierw wybierz trasę',''));timeSelect.disabled=!r;r?.times.forEach(t=>timeSelect.add(new Option(t,t)));message.textContent=''};
$('#showSchedule').onclick=()=>{const r=getRoute(routes,routeSelect.value),t=timeSelect.value;if(!r||!t){message.textContent='Wybierz trasę i godzinę zmiany.';return}$('#scheduleTitle').textContent=`${r.name} · ${t}`;$('#scheduleBody').replaceChildren(...getSchedule(r,t).map(stopRow));showView('#scheduleView')}; $('#backFromSchedule').onclick=()=>showView('#selectionView');
async function apiPost(data){const res=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(data),cache:'no-store'});if(!res.ok)throw new Error('Błąd połączenia z serwerem.');return res.json()}
$('#adminLock').onclick=()=>{$('#adminPassword').value='';$('#adminLoginMessage').textContent='';showView('#adminLoginView');setTimeout(()=>$('#adminPassword').focus(),0)};
$('#backFromLogin').onclick=()=>showView('#selectionView'); $('#backFromAdmin').onclick=()=>showView('#selectionView'); $('#backToAdmin').onclick=()=>showView('#adminView');
async function adminLogin(){const password=$('#adminPassword').value,msg=$('#adminLoginMessage');if(!password){msg.textContent='Wpisz hasło administratora.';return}msg.textContent='Sprawdzanie hasła…';try{const r=await apiPost({action:'login',password});if(r.status==='success'){msg.textContent='';$('#adminPassword').value='';renderAdminRoutes();showView('#adminView')}else msg.textContent=r.message||'Błędne hasło.'}catch(e){msg.textContent=e.message||'Nie udało się połączyć z serwerem.'}}
$('#adminLoginButton').onclick=adminLogin; $('#adminPassword').addEventListener('keydown',e=>{if(e.key==='Enter')adminLogin()});
$('#forgotPasswordButton').onclick=()=>{$('#adminResetCode').value='';$('#adminNewPassword').value='';$('#adminResetMessage').textContent='';showView('#adminResetView')}; $('#backFromReset').onclick=()=>showView('#adminLoginView');
$('#sendResetCodeButton').onclick=async()=>{const msg=$('#adminResetMessage');msg.textContent='Wysyłanie kodu…';try{const r=await apiPost({action:'forgotPassword'});msg.textContent=r.message||(r.status==='success'?'Kod został wysłany.':'Nie udało się wysłać kodu.')}catch(e){msg.textContent=e.message||'Nie udało się połączyć z serwerem.'}};
$('#resetPasswordButton').onclick=async()=>{const code=$('#adminResetCode').value.trim(),newPassword=$('#adminNewPassword').value,msg=$('#adminResetMessage');if(!code||!newPassword){msg.textContent='Wpisz kod z e-maila i nowe hasło.';return}msg.textContent='Zmiana hasła…';try{const r=await apiPost({action:'resetPassword',code,newPassword});msg.textContent=r.message||'';if(r.status==='success'){setTimeout(()=>{showView('#adminLoginView');$('#adminPassword').focus();$('#adminLoginMessage').textContent='Hasło zostało zmienione. Zaloguj się nowym hasłem.'},800)}}catch(e){msg.textContent=e.message||'Nie udało się połączyć z serwerem.'}};
$('#changePasswordButton').onclick=()=>{$('#adminOldPassword').value='';$('#adminChangePassword').value='';$('#adminChangePasswordRepeat').value='';$('#adminChangePasswordMessage').textContent='';showView('#adminChangePasswordView')}; $('#backFromChangePassword').onclick=()=>showView('#adminLoginView');
$('#saveChangedPassword').onclick=async()=>{const old=$('#adminOldPassword').value,p=$('#adminChangePassword').value,rp=$('#adminChangePasswordRepeat').value,msg=$('#adminChangePasswordMessage');if(!old){msg.textContent='Wpisz stare hasło.';return}if(p.length<4){msg.textContent='Nowe hasło musi mieć co najmniej 4 znaki.';return}if(p!==rp){msg.textContent='Nowe hasła nie są takie same.';return}msg.textContent='Sprawdzanie starego hasła…';try{const check=await apiPost({action:'login',password:old});if(check.status!=='success'){msg.textContent='Stare hasło jest nieprawidłowe.';return}msg.textContent='Zapisywanie nowego hasła…';const r=await apiPost({action:'updateAdminData',newPassword:p});if(r.status==='success'){msg.textContent='Hasło zostało zmienione.';setTimeout(()=>{$('#adminPassword').value='';$('#adminLoginMessage').textContent='Hasło zostało zmienione. Zaloguj się nowym hasłem.';showView('#adminLoginView')},700)}else msg.textContent=r.message||'Nie udało się zmienić hasła.'}catch(e){msg.textContent=e.message||'Nie udało się połączyć z serwerem.'}};
function renderAdminRoutes(){const box=$('#adminRouteList');box.replaceChildren(...routes.map(r=>{const c=document.createElement('div');c.className='adminCard';c.innerHTML=`<div class="adminCardTitle"></div><div class="cardActions"><button class="editButton">EDYTUJ TRASĘ</button><button class="danger">USUŃ TRASĘ</button></div>`;c.querySelector('.adminCardTitle').textContent=r.name;c.querySelector('.editButton').onclick=()=>openAdminRoute(r);c.querySelector('.danger').onclick=()=>alert('Usuwanie trasy zostanie aktywowane po podłączeniu bezpiecznego zapisu do arkusza.');return c}))}
function openAdminRoute(r){currentAdminRoute=r;$('#adminEditTitle').textContent=`Edycja: ${r.name}`;$('#adminCourses').replaceChildren(...r.times.map(t=>{const x=document.createElement('span');x.className='chip';x.textContent=t;return x}));$('#adminStops').replaceChildren(...r.stops.map(s=>{const c=document.createElement('div');c.className='adminCard';const title=document.createElement('div');title.className='adminCardTitle';title.textContent=s.name;const times=document.createElement('div');times.className='stopTimes';r.times.forEach(t=>{const x=document.createElement('span');x.textContent=`${t} → ${s.times?.[t]??'—'}`;times.append(x)});const actions=document.createElement('div');actions.className='cardActions';actions.innerHTML='<button class="editButton">EDYTUJ</button><button class="danger">USUŃ PRZYSTANEK</button>';actions.querySelectorAll('button').forEach(b=>b.onclick=()=>alert('Edycja zapisu zostanie aktywowana po podłączeniu API administratora.'));c.append(title,times,actions);return c}));showView('#adminEditView')}
['#addRoute','#addCourse','#removeCourse','#addStop'].forEach(id=>$(id).onclick=()=>alert('Ta operacja jest już przygotowana w panelu. W następnym kroku podłączymy zapis do arkusza.'));
const wakeBtn=$('#wakeLockButton'),wakeLabel=$('#wakeLockLabel');wakeBtn.onclick=async()=>wakeWanted?disableWake():enableWake();async function enableWake(){if(!('wakeLock'in navigator)){message.textContent='Przeglądarka nie obsługuje podtrzymania ekranu.';return}wakeWanted=true;try{wakeLock=await navigator.wakeLock.request('screen');renderWake(true)}catch{renderWake(false)}}async function disableWake(){wakeWanted=false;if(wakeLock)try{await wakeLock.release()}catch{}wakeLock=null;renderWake(false)}function renderWake(on){wakeBtn.classList.toggle('active',on);wakeLabel.textContent=on?'EKRAN ON':'EKRAN OFF'}document.addEventListener('visibilitychange',()=>{if(!document.hidden){syncRoutes();if(wakeWanted)enableWake()}});
function normalize(data){if(!data||typeof data!=='object')return[];const arr=Array.isArray(data)?data:Object.entries(data).map(([name,v])=>({...v,name:v.name??name}));return arr.map(v=>{const name=String(v.name??v.nazwa??'').trim(),raw=v.stops??v.przystanki??[],times=[...new Set((v.times??v.godziny??[]).map(String).filter(Boolean))];const stops=raw.map(s=>{if(Array.isArray(s)){const[n,coords,vals=[]]=s,o={};times.forEach((t,i)=>o[t]=vals[i]??null);return{name:String(n??''),coordinates:String(coords??''),times:o}}const o={};const src=s.times??s.godziny??{};if(Array.isArray(src))times.forEach((t,i)=>o[t]=src[i]??null);else Object.entries(src).forEach(([k,val])=>o[String(k)]=val??null);return{name:String(s.name??s.nazwa??s.przystanek??''),coordinates:String(s.coordinates??s.lokalizacja??s.coords??''),times:o}}).filter(s=>s.name);if(!times.length)stops.forEach(s=>Object.keys(s.times).forEach(t=>{if(!times.includes(t))times.push(t)}));return{name,times,stops}}).filter(valid)}
function valid(r){return r?.name&&r.times?.length&&r.stops?.length}async function syncRoutes(){if(syncing)return;syncing=true;try{const res=await fetch(`${API_URL}?t=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw 0;const p=await res.json(),fresh=normalize(p?.data??p);if(!fresh.length)throw 0;routes=fresh;localStorage.setItem(DATA_KEY,JSON.stringify(routes));localStorage.setItem(SYNC_KEY,Date.now());localStorage.removeItem(FAIL_KEY);offline=false;renderRoutes();if(!$('#adminView').hidden)renderAdminRoutes()}catch{if(!localStorage.getItem(FAIL_KEY))localStorage.setItem(FAIL_KEY,Date.now());offline=true}finally{syncing=false;updateStatus()}}function loadCached(){try{const x=JSON.parse(localStorage.getItem(DATA_KEY));return Array.isArray(x)&&x.every(valid)?x:null}catch{return null}}function renderRoutes(){const old=routeSelect.value;routeSelect.replaceChildren(new Option('Wybierz trasę',''));routes.forEach(r=>routeSelect.add(new Option(r.name,r.name)));if(routes.some(r=>r.name===old))routeSelect.value=old}function updateStatus(){const last=+localStorage.getItem(SYNC_KEY)||0,fail=+localStorage.getItem(FAIL_KEY)||0,ref=last||fail;if(!offline){connectionStatus.hidden=true;staleWarning.hidden=true;return}connectionStatus.hidden=false;connectionStatus.textContent=last?'Offline · dane zapisane lokalnie':'Offline · brak świeżej synchronizacji';staleWarning.hidden=!ref||Date.now()-ref<THREE_DAYS}function stopRow(s){const tr=document.createElement('tr'),a=document.createElement('td'),b=document.createElement('td'),c=document.createElement('td');a.textContent=s.name;b.textContent=s.time??'Koniec trasy';const u=mapUrl(s.coordinates);if(u){const l=document.createElement('a');l.href=u;l.target='_blank';l.rel='noopener';l.textContent='MAPA';c.append(l)}else c.textContent='—';tr.append(a,b,c);return tr}
let promptInstall=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptInstall=e;$('#installBanner').hidden=false});$('#installButton').onclick=async()=>{if(promptInstall){promptInstall.prompt();await promptInstall.userChoice;$('#installBanner').hidden=true;promptInstall=null}};$('#rejectInstall').onclick=()=>$('#installBanner').hidden=true;
if('serviceWorker'in navigator)window.addEventListener('load',async()=>{const reg=await navigator.serviceWorker.register('./sw.js');const notice=()=>{if(reg.waiting)$('#updateNotice').hidden=false};notice();reg.addEventListener('updatefound',()=>reg.installing?.addEventListener('statechange',()=>{if(reg.installing?.state==='installed'&&navigator.serviceWorker.controller)notice()}));$('#updateAppButton').onclick=()=>reg.waiting?.postMessage({type:'SKIP_WAITING'});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload());reg.update()});