(()=>{
  const body=document.getElementById('scheduleBody'),view=document.getElementById('scheduleView');
  if(!body||!view||!navigator.geolocation)return;
  const TOLERANCE_SECONDS=30,ROUTE_REFRESH_MS=12000,MAX_GPS_ACCURACY=120;
  let pos=null,watch=null,lastRouteAt=0,lastTarget=null,etaSeconds=null,requesting=false;
  const style=document.createElement('style');style.textContent=`#scheduleBody .punctualityLamp{display:none!important}#scheduleBody .etaPunctuality{display:inline-flex;align-items:center;justify-content:center;margin-left:8px;padding:4px 7px;border-radius:999px;font-size:.67rem;font-weight:1000;letter-spacing:.04em;white-space:nowrap;color:#111}#scheduleBody .etaPunctuality.onTime{background:#55ef61;box-shadow:0 0 7px #55ef61,0 0 15px #55ef61}#scheduleBody .etaPunctuality.early{background:#ffd83d;box-shadow:0 0 7px #ffd83d,0 0 15px #ffd83d}#scheduleBody .etaPunctuality.late{background:#ff4d4d;color:#fff;box-shadow:0 0 7px #ff4d4d,0 0 15px #ff4d4d}`;document.head.append(style);
  function coord(v){const m=String(v||'').match(/(-?\d+(?:\.\d+)?)\s*[,; ]\s*(-?\d+(?:\.\d+)?)/);return m?[+m[1],+m[2]]:null}
  function schedSeconds(row){const m=String(row?.children[1]?.firstChild?.textContent||row?.children[1]?.textContent||'').trim().match(/^(\d{1,2}):(\d{2})/);if(!m)return null;const n=new Date(),d=new Date(n);d.setHours(+m[1],+m[2],0,0);return (d-n)/1000}
  function meters(a,b){const R=6371000,p=Math.PI/180,dLat=(b[0]-a[0])*p,dLng=(b[1]-a[1])*p,x=Math.sin(dLat/2)**2+Math.cos(a[0]*p)*Math.cos(b[0]*p)*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
  function targetRow(){if(!pos)return null;const rows=[...body.querySelectorAll('tr')],here=[pos.lat,pos.lng];let best=null,bestScore=Infinity;for(const r of rows){const c=coord(r.dataset.coordinate),s=schedSeconds(r);if(!c||s===null||s < -1800 || s > 3600)continue;const d=meters(here,c);const score=d+Math.abs(s)*2;if(score<bestScore){bestScore=score;best={row:r,c,d,s}}}return best}
  async function refreshEta(target){if(requesting||!target||!pos)return;if(Date.now()-lastRouteAt<ROUTE_REFRESH_MS&&lastTarget===target.row)return;requesting=true;lastRouteAt=Date.now();lastTarget=target.row;try{const u=`https://router.project-osrm.org/route/v1/driving/${pos.lng},${pos.lat};${target.c[1]},${target.c[0]}?overview=false&steps=false`;const r=await fetch(u,{cache:'no-store'});const j=await r.json();etaSeconds=j?.routes?.[0]?.duration??null}catch{etaSeconds=null}finally{requesting=false}}
  function labelSeconds(v){const a=Math.abs(Math.round(v));if(a<60)return `${a} S`;const m=Math.floor(a/60),s=a%60;return s?`${m}:${String(s).padStart(2,'0')} MIN`:`${m} MIN`}
  function render(){if(view.hidden)return;document.querySelectorAll('#scheduleBody .etaPunctuality').forEach(x=>x.remove());const t=targetRow();if(!t||etaSeconds===null)return;refreshEta(t);const scheduleLeft=schedSeconds(t.row);if(scheduleLeft===null)return;const diff=etaSeconds-scheduleLeft;const lamp=document.createElement('span');lamp.className='etaPunctuality';if(diff>TOLERANCE_SECONDS){lamp.classList.add('late');lamp.textContent=`+${labelSeconds(diff)} SPÓŹNIENIA`}else if(diff<-TOLERANCE_SECONDS){lamp.classList.add('early');lamp.textContent=`${labelSeconds(diff)} ZA WCZEŚNIE`}else{lamp.classList.add('onTime');lamp.textContent='O CZASIE'}t.row.children[1]?.append(lamp)}
  function start(){if(watch!==null)return;watch=navigator.geolocation.watchPosition(p=>{pos={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy||999};if(pos.accuracy<=MAX_GPS_ACCURACY){const t=targetRow();refreshEta(t).then(render)}},{},{enableHighAccuracy:true,maximumAge:1000,timeout:15000})}
  start();setInterval(()=>{if(!view.hidden&&pos?.accuracy<=MAX_GPS_ACCURACY){const t=targetRow();refreshEta(t);render()}},1000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')start()});
})();