let map=null,marker=null,mapsLoading=null;
const $=s=>document.querySelector(s);
const API_URL='https://script.google.com/macros/s/AKfycbzdG_ARbbPgMdlPteqFLakZHR5EEkT4Lb3YFDbXW_I_OyrDKo8l0_KrQLjnncxj_M9q/exec';
function number(v,fallback){const n=parseFloat(String(v??'').replace(',','.'));return Number.isFinite(n)?n:fallback}
function updateFields(lat,lng){$('#mapLat').value=lat.toFixed(6);$('#mapLng').value=lng.toFixed(6)}
async function getMapsKey(){const password=$('#adminPassword')?.value||'';if(!password)throw new Error('Brak hasła administratora. Zaloguj się ponownie.');const res=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'getMapsApiKey',password}),cache:'no-store'});const data=await res.json();if(data.status!=='success'||!data.apiKey)throw new Error(data.message||'Nie udało się pobrać klucza Google Maps.');return data.apiKey}
async function loadGoogleMaps(){if(window.google?.maps)return;if(mapsLoading)return mapsLoading;mapsLoading=(async()=>{const key=await getMapsKey();await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://maps.googleapis.com/maps/api/js?key='+encodeURIComponent(key)+'&v=weekly';s.async=true;s.defer=true;s.onload=resolve;s.onerror=()=>reject(new Error('Nie udało się uruchomić Google Maps.'));document.head.appendChild(s)})})();try{await mapsLoading}catch(e){mapsLoading=null;throw e}}
async function initMap(){const box=$('#mapPicker');if(!box)return;const lat=number($('#mapLat')?.value,52),lng=number($('#mapLng')?.value,19);box.innerHTML='<div id="interactiveMap" style="position:absolute;inset:0"></div>';try{await loadGoogleMaps();const pos={lat,lng};map=new google.maps.Map($('#interactiveMap'),{center:pos,zoom:17,mapTypeControl:false,streetViewControl:false,fullscreenControl:true,gestureHandling:'greedy'});marker=new google.maps.Marker({position:pos,map,draggable:true,title:'Przeciągnij pinezkę'});marker.addListener('dragend',()=>{const p=marker.getPosition();updateFields(p.lat(),p.lng());map.panTo(p)});map.addListener('click',e=>{marker.setPosition(e.latLng);updateFields(e.latLng.lat(),e.latLng.lng())});}catch(e){box.innerHTML='<div style="padding:20px;text-align:center">'+String(e.message||e)+'</div>'}}
window.trasyInitGoogleMap=initMap;
const observer=new MutationObserver(()=>{const view=$('#mapEditView');if(view&&!view.hidden)setTimeout(initMap,0)});
window.addEventListener('DOMContentLoaded',()=>{const view=$('#mapEditView');if(view)observer.observe(view,{attributes:true,attributeFilter:['hidden']});const moveToFields=()=>{if(map&&marker){const pos={lat:number($('#mapLat').value,52),lng:number($('#mapLng').value,19)};map.setCenter(pos);marker.setPosition(pos)}};$('#mapLat')?.addEventListener('change',moveToFields);$('#mapLng')?.addEventListener('change',moveToFields);$('#useDeviceLocation')?.addEventListener('click',()=>setTimeout(()=>{if(map&&marker){const pos={lat:number($('#mapLat').value,52),lng:number($('#mapLng').value,19)};map.setCenter(pos);map.setZoom(18);marker.setPosition(pos)}},300))});