(()=>{
  const body=document.getElementById('scheduleBody');
  if(!body)return;
  let map=null,positionMarker=null,watchId=null,steps=[],routeCoords=[],rerouteTimer=0,lastSpoken='';
  let autoCenter=true,currentStops=[],lastGpsPoint=null,currentHeading=0,stopMarkers=[];
  const PITCH=58,ZOOM=17.2;
  const panel=document.createElement('section');
  panel.id='routeMapNav';panel.hidden=true;
  panel.innerHTML=`<div style="position:fixed;inset:0;z-index:40000;background:#111;display:flex;flex-direction:column"><div style="display:flex;align-items:center;gap:8px;padding:8px 10px;background:#181818;border-bottom:2px solid #ccff33"><button id="routeMapClose" type="button" style="width:auto;min-width:84px">ZAKOŃCZ</button><strong style="flex:1;text-align:center;color:#ccff33">NAWIGACJA</strong><button id="routeMapCenter" type="button" style="width:auto;min-width:84px">CENTRUJ</button></div><div style="background:#222;padding:10px 12px;border-bottom:1px solid #444"><div id="routeManeuver" style="font-size:22px;font-weight:900;line-height:1.15">Pobieranie trasy…</div><div style="display:flex;justify-content:space-between;gap:12px;margin-top:5px"><span id="routeManeuverDistance" style="font-size:19px;font-weight:900;color:#ccff33"></span><span id="routeNextStop" style="font-size:14px;color:#ddd;text-align:right"></span></div></div><div id="routeMapCanvas" style="flex:1;min-height:0;overflow:hidden"></div><div id="routeMapStatus" style="padding:8px 12px;background:#181818;color:#fff;font-weight:800;text-align:center">Pobieranie pozycji…</div></div>`;
  document.body.append(panel);
  const status=panel.querySelector('#routeMapStatus'),maneuverEl=panel.querySelector('#routeManeuver'),maneuverDistance=panel.querySelector('#routeManeuverDistance'),nextStopEl=panel.querySelector('#routeNextStop');
  panel.querySelector('#routeMapClose').onclick=closeMapNav;
  panel.querySelector('#routeMapCenter').onclick=()=>{autoCenter=true;if(positionMarker&&map)followCamera([positionMarker.getLngLat().lat,positionMarker.getLngLat().lng],currentHeading,true)};
  function closeMapNav(){if(watchId!==null){navigator.geolocation.clearWatch(watchId);watchId=null}panel.hidden=true;speechSynthesis?.cancel?.();lastGpsPoint=null;currentHeading=0}
  function parseCoord(s){const m=String(s||'').match(/(-?\d+(?:\.\d+)?)\s*[,; ]\s*(-?\d+(?:\.\d+)?)/);return m?[+m[1],+m[2]]:null}
  function posOnce(){return new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:12000,maximumAge:3000}))}
  function fmtDistance(m){return m<950?`${Math.max(10,Math.round(m/10)*10)} m`:`${(m/1000).toFixed(m<10000?1:0)} km`}
  function markerElement(text,color,size=28){const el=document.createElement('div');el.style.cssText=`width:${size}px;height:${size}px;border-radius:50%;background:${color};border:3px solid #fff;box-shadow:0 2px 8px #0009;display:flex;align-items:center;justify-content:center;color:#111;font-weight:900;font-size:${size<30?10:13}px`;el.textContent=text;return el}
  function hav(a,b){const R=6371000,p=Math.PI/180,dLat=(b[0]-a[0])*p,dLon=(b[1]-a[1])*p,x=Math.sin(dLat/2)**2+Math.cos(a[0]*p)*Math.cos(b[0]*p)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
  function bearing(a,b){const p=Math.PI/180,lat1=a[0]*p,lat2=b[0]*p,dLon=(b[1]-a[1])*p;const y=Math.sin(dLon)*Math.cos(lat2),x=Math.cos(lat1)*Math.sin(lat2)-Math.sin(lat1)*Math.cos(lat2)*Math.cos(dLon);return(Math.atan2(y,x)*180/Math.PI+360)%360}
  function smoothHeading(next){if(!Number.isFinite(next))return currentHeading;let d=((next-currentHeading+540)%360)-180;currentHeading=(currentHeading+d*.28+360)%360;return currentHeading}
  function headingFromPosition(p,ll){let h=Number(p.coords.heading);if(!Number.isFinite(h)||h<0){if(lastGpsPoint&&hav(lastGpsPoint,ll)>=3)h=bearing(lastGpsPoint,ll);else h=currentHeading}if(!lastGpsPoint||hav(lastGpsPoint,ll)>=2)lastGpsPoint=ll;return smoothHeading(h)}
  function followCamera(ll,heading,instant=false){if(!map||!autoCenter)return;const h=map.getContainer().clientHeight||600;map.easeTo({center:[ll[1],ll[0]],zoom:ZOOM,bearing:heading,pitch:PITCH,offset:[0,Math.round(h*.18)],duration:instant?0:420,essential:true})}
  function instruction(step){const m=step?.maneuver||{},type=m.type||'',mod=m.modifier||'',road=step.name?` w ${step.name}`:'';const dir={left:'w lewo',right:'w prawo','slight left':'lekko w lewo','slight right':'lekko w prawo','sharp left':'ostro w lewo','sharp right':'ostro w prawo',straight:'prosto',uturn:'zawróć'}[mod]||'';if(type==='depart')return dir?`Rusz ${dir}`:'Rusz prosto';if(type==='arrive')return'Dojeżdżasz do punktu';if(type==='roundabout'||type==='rotary')return`Wjedź na rondo${m.exit?` i wybierz ${m.exit}. zjazd`:''}`;if(type==='merge')return`Włącz się ${dir}`.trim();if(type==='fork')return`Na rozwidleniu trzymaj się ${dir}`.trim();if(type==='on ramp')return`Wjedź na zjazd ${dir}`.trim();if(type==='off ramp')return`Zjedź ${dir}`.trim();if(type==='end of road')return`Na końcu drogi skręć ${dir}${road}`.trim();if(type==='continue')return`Jedź ${dir||'prosto'}${road}`.trim();if(type==='turn'||type==='new name')return`Skręć ${dir}${road}`.trim();return`${dir?`Jedź ${dir}`:'Jedź prosto'}${road}`.trim()}
  function isVoiceManeuver(step){const m=step?.maneuver||{},type=m.type||'',mod=m.modifier||'';if(type==='arrive'||type==='roundabout'||type==='rotary'||type==='merge'||type==='fork'||type==='on ramp'||type==='off ramp'||type==='end of road')return true;if(type==='turn')return mod&&mod!=='straight';if(type==='new name')return mod&&mod!=='straight';if(type==='continue')return mod&&mod!=='straight';return false}
  function nearestStep(ll){let best=null,bestD=Infinity;for(const s of steps){const loc=s.maneuver?.location;if(!loc)continue;const d=hav(ll,[loc[1],loc[0]]);if(d<bestD){bestD=d;best=s}}return{step:best,distance:bestD}}
  function nearestRouteDistance(ll){let best=Infinity;for(let i=0;i<routeCoords.length;i+=Math.max(1,Math.floor(routeCoords.length/500)))best=Math.min(best,hav(ll,routeCoords[i]));return best}
  function speak(step,text,d){if(!isVoiceManeuver(step))return;let bucket=d<65?'now':d<220?'200':d<550?'500':'';if(!bucket)return;const key=(step.maneuver?.type||'')+'|'+(step.maneuver?.modifier||'')+'|'+(step.name||'')+'|'+bucket;if(key===lastSpoken)return;lastSpoken=key;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(bucket==='now'?text:`Za ${bucket==='200'?'200':'500'} metrów. ${text}`);u.lang='pl-PL';speechSynthesis.speak(u)}catch{}}
  function remainingStopsFromGps(){const rows=[...body.querySelectorAll('tr')];let idx=Number(body.dataset.gpsNextStop);if(!Number.isInteger(idx)||idx<0||idx>=rows.length){const active=rows.findIndex(r=>r.classList.contains('gpsNextStop'));idx=active>=0?active:0}return rows.slice(idx).map((r,i)=>({coord:parseCoord(r.dataset.coordinate),name:r.querySelector('td:first-child')?.innerText.trim()||`Punkt ${i+1}`})).filter(x=>x.coord)}
  function updateGuidance(ll){const {step,distance}=nearestStep(ll);if(!step)return;const text=instruction(step);maneuverEl.textContent=text;maneuverDistance.textContent=fmtDistance(distance);speak(step,text,distance);if(currentStops.length){let best=currentStops[0],d=hav(ll,best.coord);for(const s of currentStops){const x=hav(ll,s.coord);if(x<d){best=s;d=x}}nextStopEl.textContent=`Najbliższy punkt: ${best.name}`}const off=nearestRouteDistance(ll);status.textContent=off>80?'Poza trasą — przeliczam…':`Na trasie • dokładność GPS ${Math.round(window.__navAcc||0)} m`;if(off>80&&!rerouteTimer)rerouteTimer=setTimeout(()=>{rerouteTimer=0;const remaining=remainingStopsFromGps();if(remaining.length){currentStops=remaining;buildRoute(ll,currentStops)}},1800)}
  function routeGeoJSON(coords){return{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:coords}}}
  async function buildRoute(origin,stops){const coords=[origin,...stops.map(s=>s.coord)].map(([lat,lng])=>`${lng},${lat}`).join(';');status.textContent='Pobieranie przebiegu trasy…';const res=await fetch(`https://router.project-osrm.org/route/v1/driving/${coords}?overview=full&geometries=geojson&steps=true`,{cache:'no-store'});if(!res.ok)throw Error(`HTTP ${res.status}`);const data=await res.json(),route=data.routes?.[0];if(!route)throw Error('Nie znaleziono trasy.');const geo=routeGeoJSON(route.geometry.coordinates);routeCoords=(route.geometry?.coordinates||[]).map(([lng,lat])=>[lat,lng]);steps=(route.legs||[]).flatMap(l=>l.steps||[]);if(map.getSource('route'))map.getSource('route').setData(geo);else{map.addSource('route',{type:'geojson',data:geo});map.addLayer({id:'route-outline',type:'line',source:'route',layout:{'line-cap':'round','line-join':'round'},paint:{'line-color':'#202020','line-width':11,'line-opacity':.7}});map.addLayer({id:'route-line',type:'line',source:'route',layout:{'line-cap':'round','line-join':'round'},paint:{'line-color':'#ccff33','line-width':7,'line-opacity':.95}})}status.textContent=`Trasa ${fmtDistance(route.distance)} • ${Math.round(route.duration/60)} min`}
  function clearMarkers(){if(positionMarker){positionMarker.remove();positionMarker=null}stopMarkers.forEach(m=>m.remove());stopMarkers=[]}
  async function openMapNav(){if(!window.maplibregl){alert('Mapa nie została załadowana. Sprawdź połączenie z internetem.');return}const stops=remainingStopsFromGps();if(!stops.length){alert('Brak pozostałych punktów trasy.');return}if(!navigator.geolocation){alert('Telefon nie udostępnia lokalizacji.');return}currentStops=stops;panel.hidden=false;status.textContent='Pobieranie pozycji telefonu…';maneuverEl.textContent='Pobieranie trasy…';maneuverDistance.textContent='';nextStopEl.textContent='';autoCenter=true;lastSpoken='';lastGpsPoint=null;currentHeading=0;try{const pos=await posOnce(),origin=[pos.coords.latitude,pos.coords.longitude];window.__navAcc=pos.coords.accuracy||0;if(!map){map=new maplibregl.Map({container:'routeMapCanvas',style:{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]},center:[origin[1],origin[0]],zoom:ZOOM,pitch:PITCH,bearing:0,attributionControl:true,maxPitch:60});map.addControl(new maplibregl.NavigationControl({showCompass:true,showZoom:true}),'bottom-right');map.on('dragstart',e=>{if(e.originalEvent)autoCenter=false});await new Promise(resolve=>map.loaded()?resolve():map.once('load',resolve))}else{map.resize();if(map.getSource('route'))map.getSource('route').setData(routeGeoJSON([]))}clearMarkers();positionMarker=new maplibregl.Marker({element:markerElement('▲','#ccff33',34),rotationAlignment:'viewport',pitchAlignment:'viewport',subpixelPositioning:true}).setLngLat([origin[1],origin[0]]).addTo(map);stops.forEach((s,i)=>{const marker=new maplibregl.Marker({element:markerElement(String(i+1),i===stops.length-1?'#ffb000':'#078df0')}).setLngLat([s.coord[1],s.coord[0]]).setPopup(new maplibregl.Popup({offset:18}).setText(s.name)).addTo(map);stopMarkers.push(marker)});await buildRoute(origin,stops);updateGuidance(origin);followCamera(origin,0,true);if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=navigator.geolocation.watchPosition(p=>{const ll=[p.coords.latitude,p.coords.longitude];window.__navAcc=p.coords.accuracy||0;if(positionMarker)positionMarker.setLngLat([ll[1],ll[0]]);const h=headingFromPosition(p,ll);if(positionMarker)positionMarker.setRotation(0);followCamera(ll,h,false);updateGuidance(ll)},()=>{status.textContent='Brak aktualnej pozycji GPS.'},{enableHighAccuracy:true,maximumAge:500,timeout:15000})}catch(e){status.textContent=`Nie udało się uruchomić nawigacji: ${e.message||'błąd'}`}}
  body.addEventListener('gps-next-stop-change',e=>{if(panel.hidden)return;const remaining=remainingStopsFromGps();if(!remaining.length)return;currentStops=remaining;if(lastGpsPoint){clearTimeout(rerouteTimer);rerouteTimer=setTimeout(()=>{rerouteTimer=0;buildRoute(lastGpsPoint,currentStops)},250)}});
  body.addEventListener('route-direction-change',()=>{if(panel.hidden)return;const remaining=remainingStopsFromGps();if(!remaining.length)return;currentStops=remaining;if(lastGpsPoint){clearTimeout(rerouteTimer);rerouteTimer=setTimeout(()=>{rerouteTimer=0;buildRoute(lastGpsPoint,currentStops)},250)}});
  document.addEventListener('click',e=>{const link=e.target.closest?.('.routeLink');if(!link||!body.contains(link))return;e.preventDefault();e.stopImmediatePropagation();openMapNav()},true)
})();