import { effectiveVehicleSpeedLimit } from './vehicle-speed-profile-core.js';

(()=>{
  const controls=document.querySelector('#scheduleView .scheduleControls'),heading=document.querySelector('#scheduleView .scheduleHeading');if(!controls||!heading)return;
  const style=document.createElement('style');style.textContent=`
    #scheduleSpeedBox{display:inline-flex;align-items:center;gap:10px;white-space:nowrap;z-index:2}#scheduleSpeedBox .routeSpeedLimit{width:54px;height:54px;border-width:5px;font-size:22px}#scheduleSpeedBox .routeCurrentSpeed{min-width:68px;font-size:30px}#scheduleSpeedBox .routeCurrentSpeed small{font-size:10px}.routeSpeedLimitWrap{display:grid;justify-items:center}.routeSpeedLimit{width:40px;height:40px;border:4px solid #e11d2e;border-radius:50%;background:#fff;color:#111;display:flex;align-items:center;justify-content:center;font:1000 17px/1 Arial,sans-serif;box-sizing:border-box}.routeSpeedLimit.unknown{color:#666;border-color:#777}.routeCurrentSpeed{min-width:58px;text-align:center;font:1000 22px/1 Arial,sans-serif;color:#fff}.routeCurrentSpeed small{display:block;margin-top:2px;font-size:8px;color:#aaa;letter-spacing:.05em}.routeCurrentSpeed.over{color:#ff453a}
    #routeMapSpeedBox{position:absolute;left:12px;bottom:12px;z-index:50100;display:flex;align-items:flex-end;gap:8px;padding:7px 8px;border-radius:12px;background:#111c;box-shadow:0 2px 9px #0009;pointer-events:none}#routeMapSpeedBox .routeSpeedLimit{width:48px;height:48px;font-size:20px;border-width:4px}#routeMapSpeedBox .routeCurrentSpeed{min-width:58px;font-size:26px;text-shadow:0 1px 2px #000}#routeMapSpeedBox .routeCurrentSpeed small{font-size:9px}@media(max-width:520px){#scheduleSpeedBox{gap:7px}#scheduleSpeedBox .routeSpeedLimit{width:48px;height:48px;font-size:20px;border-width:4px}#scheduleSpeedBox .routeCurrentSpeed{min-width:60px;font-size:27px}#routeMapSpeedBox{left:10px;bottom:10px}}
  `;document.head.append(style);
  const speedMarkup='<span class="routeSpeedLimitWrap"><span class="routeSpeedLimit unknown" aria-label="Brak danych o ograniczeniu prędkości">—</span></span><span class="routeCurrentSpeed">0<small>km/h</small></span>';
  const box=document.createElement('div');box.id='scheduleSpeedBox';box.setAttribute('aria-label','Prędkość i ograniczenie prędkości');box.innerHTML=speedMarkup;heading.append(box);
  let mapBox=null;function ensureMapBox(){const canvas=document.getElementById('routeMapCanvas');if(!canvas)return null;if(mapBox?.isConnected)return mapBox;const cs=getComputedStyle(canvas);if(cs.position==='static')canvas.style.position='relative';mapBox=document.createElement('div');mapBox.id='routeMapSpeedBox';mapBox.setAttribute('aria-label','Prędkość i ograniczenie prędkości');mapBox.innerHTML=speedMarkup;canvas.appendChild(mapBox);return mapBox}
  function state(){return effectiveVehicleSpeedLimit({roadLimit:window.__routeRoadSpeedLimitKmh,roadClass:window.__routeRoadClass,highSpeedRoad:window.__routeHighSpeedRoad,vehicle:window.__selectedVehicle})}
  function renderOne(parent){if(!parent)return;const limitEl=parent.querySelector('.routeSpeedLimit'),speedEl=parent.querySelector('.routeCurrentSpeed');const speed=Math.max(0,Number(window.__routeCurrentSpeedKmh)||0),result=state(),limit=result.limit;limitEl.textContent=limit?String(Math.round(limit)):'—';limitEl.classList.toggle('unknown',!limit);limitEl.setAttribute('aria-label',limit?`Ograniczenie prędkości ${Math.round(limit)} kilometrów na godzinę`:'Brak danych o ograniczeniu prędkości');limitEl.removeAttribute('title');speedEl.innerHTML=`${Math.round(speed)}<small>km/h</small>`;speedEl.classList.toggle('over',!!limit&&speed>limit+2)}
  function render(){renderOne(box);renderOne(ensureMapBox())}document.addEventListener('trasy:gps-speed',render);document.addEventListener('trasy:selected-vehicle-change',render);document.addEventListener('trasy:road-speed-limit',e=>{const d=e.detail||{};window.__routeRoadSpeedLimitKmh=Number(d.maxspeed)||null;window.__routeRoadClass=d.roadClass||'';window.__routeHighSpeedRoad=!!d.highSpeedRoad;render()});setInterval(render,1000);render();
})();
